version: "3.8"

services:
  service-registry:
    container_name: service-registry
    build:
      context: service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: on-failure

  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    restart: on-failure

  employee-service:
    container_name: employee-service
    build:
      context: employee-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure

  department-service:
    container_name: department-registry
    build:
      context: department-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure

  organization-service:
    container_name: organization-registry
    build:
      context: organization-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: on-failure

  user-service:
    container_name: user-registry
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: on-failure