server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  ## Routes for Employee service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
#        locator: # ?? ???? ?? ???? ?? ?? ?? (??? ???? ???) ??? ???
#                  # http://localhost:9191/employee-service/api/v1/employee/1 ??????? employee-service? ??
#          enabled: true
#          lower-case-service-id: true

        # ?? ? ???? ???? ??? ??.
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE # Load balanced uri
          predicates:
            - Path=/api/v1/employee/** # http://localhost:9191/api/v1/employee/1 ??? ??? ???? EMPLOYEE-SERVICE? ??
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/department/**
        - id: ORGANIZATION-SERVICE
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/v1/organization/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
management:
  endpoints:
    web:
      exposure:
        include: "*" # ?? ?????? ??????.
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"




