server:
  port: ${port:8080}
  servlet:
    context-path: /api/v1
  max-http-header-size: 40MB

eureka:
  instance:
    serverUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: DEPARTMENT-SERVICE

  main:
    allow-bean-definition-overriding: true

  profiles:
    include:
      - db

  devtools:
    add-properties: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # ?? ??? ?? ??
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:/db/migration
#    baseline-version: 1

logging:
  level:
    com.springboot.blog: DEBUG

#cipher:
#  secret: XOb3v5akwe06sH3aSMPwJeZfNhfq6zOQ
#
#jwt:
#  header: Authorization
#  secret: sksmsgodqhrgkwlakstktlfrmrjtdmsgodqhrgkwldksgsmsrjtdmlqkswmddlehlrlehgksekdlrpantmsthflsiaus
#  token-validity-in-seconds: 86400
