spring:
  config:
    activate:
      on-profile:
        - db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql@123

#  flyway:
#    user: root
#    password: mysql@123