#server:
#  port: ${port:8081}
#  servlet:
#    context-path: /api/v1
#  max-http-header-size: 40MB
#
#eureka:
#  instance:
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  application:
#    name: EMPLOYEE-SERVICE
#
#  main:
#    allow-bean-definition-overriding: true
#
#  profiles:
#    include:
#      - db
#
#  devtools:
#    add-properties: false

spring:
  application:
    name: EMPLOYEE-SERVICE

  config:
    import:
      - optional:configserver:http://localhost:8888
  profiles:
    include:
      - db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50 # 실패 임계값
        minimumNumberOfCalls: 5 # 최소 호출 횟수
        automaticTransitionFromOpenToHalfOpenEnabled: true # 자동으로 Half-Open 상태로 전환
        waitDurationInOpenState: 5s # Open 상태 유지 시간
        permittedNumberOfCallsInHalfOpenState: 3 # Half-Open 상태에서 허용되는 호출 횟수
        slidingWindowSize: 10 # 실패율을 계산할 호출 횟수
        slidingWindowType: COUNT_BASED # 실패율을 계산할 방식 (COUNT_BASED, TIME_BASED)

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#  # ?? ??? ?? ??
#  servlet:
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB
#
##  flyway:
##    enabled: true
##    baseline-on-migrate: true
##    locations: classpath:/db/migration
##    baseline-version: 1
#
#logging:
#  level:
#    com.springboot.blog: DEBUG
#
##cipher:
##  secret: XOb3v5akwe06sH3aSMPwJeZfNhfq6zOQ
##
##jwt:
##  header: Authorization
##  secret: sksmsgodqhrgkwlakstktlfrmrjtdmsgodqhrgkwldksgsmsrjtdmlqkswmddlehlrlehgksekdlrpantmsthflsiaus
##  token-validity-in-seconds: 86400
